### ISSUE TITLE
+ Spring Security

### ISSUE THREAD

**Issue by JanStureNielsen** [guillefritz/spring-boot-zk#1]
Hi Guillermo,

Thanks for your Spring Boot + ZK sample -- it's the best one I've been able to find! I attempted to add Spring Security support to your sample but after login I get a 403 when I click the button. In reading a bit, it appears some ZK library/framework code may be needed to get that working but as I just started with ZK I'm quite lost. Have you been able to get ZK + Spring Boot + Spring Security to work? Any chance you could add that to your sample (or a new sample)?

Many thanks for your time.

--Jan

**Comment by guillefritz** [comment]
Hi Jan, I've added some changes to the base project, updated dependencies (java 8, spring boot 1.3, zk 8, etc) and of course the auth, a simple one

try running Application.java and login with  uuu / ppp

I made a interesting integration with twitter bootstrap, i'll add to github soon

thanks

**Comment by JanStureNielsen** [comment]
Fantastic, @guillefritz - thank you so much! Your update works exactly as I'd hoped.
